"""
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""
class Solution:
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        # return list(collections.Counter(t) - collections.Counter(s))[0]

        """
        #1: 51 ms
        """
        # s_counter = collections.Counter(s)
        # t_counter = collections.Counter(t)
        # for s_key, s_value in s_counter.items():
        #     t_counter[s_key] -= s_value
        # return [x for x in t_counter.keys() if t_counter[x] ==1 ][0]
        
        """
        #2: 33 ms
        """
        for x in set(t):
            if s.count(x) != t.count(x):
                return x